_target_: src.models.face_custom_module.FaceCustomLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

backbone:
  _target_: src.models.components.backbone_maker.BackboneMaker  
  name: resnet50 # timm format
  pretrained: true
  checkpoint_path: null

age_head:
  _target_: src.models.components.age_classifier.AgeClassifier 
  output_size: 6

gender_head:
  _target_: src.models.components.gender_classifier.GenderClassifier
  output_size: 2

# compile model for faster training with pytorch 2.0
compile: false

num_classes: [2, 6] # [4, 2, 6, 4, 7, 2] race, gender, age, skintone, emotions, masked
attributes: ["gender","age"] # ["race","gender","age","skintone","emotion","masked"]
checkpoint_dir: ${callbacks.model_checkpoint.dirpath}
